apiVersion: v1
kind: Service
metadata:
  name: hms-service
  namespace: lakehouse
  labels:
    app: hms
spec:
  selector:
    app: hms
  ports:
    - port: 9083

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hms-app
  namespace: lakehouse
  labels:
    app: hms
spec:
  serviceName: hms-service
  replicas: 1
  selector:
    matchLabels:
      app: hms
  template:
    metadata:
      labels:
        app: hms
    spec:
      containers:
        - name: hms-container
          image: hive-metastore:v3.0.0
          ports:
          - containerPort: 9083
          command: ["/opt/hive-metastore/bin/start-metastore"]
          args: ["-p", "9083"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysqldb-root-password
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: s3-access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: s3-secret-key                                    
          volumeMounts:
            - name: hms-disk
              mountPath: /data                  
  volumeClaimTemplates:
  - metadata:
      name: hms-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          #ToDo: this size is not mapping to filesystem in the pod       
          storage: 5Gi  