apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: lakehouse
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "spark-hadoop:v3.2.0"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.2.0"
  sparkConf:
    "spark.jars.ivy": "/tmp/.ivy"
  restartPolicy:
    type: Never
  volumes:
    - name: config-vol
      configMap:
        name: dummy-cm   
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.0
    serviceAccount: spark-sa
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm   
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.2.0
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm     