apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
  namespace: lakehouse
spec:
  template:
    spec:
      initContainers:
        - name: initdb
          image: mysql-conn:v3.0.0
          command: ["mysql"]
          args: ["-u" ,"root" ,"-p$(MYSQL_ROOT_PASSWORD)",
                  "-h", "mysqldb-service.lakehouse.svc.cluster.local",
                  "-P", "3306",
                  "-e", "create database if not exists metastore_db"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysqldb-root-password
      containers:
        - name: initschema
          image: mysql-conn:v3.0.0
          command: ["mysql"]
          args: ["-u" ,"root" ,"-p$(MYSQL_ROOT_PASSWORD)" ,
                  "-h", "mysqldb-service.lakehouse.svc.cluster.local",
                  "-P", "3306",
                  "metastore_db",
                  "-e", "source /opt/hive-metastore/scripts/metastore/upgrade/mysql/hive-schema-3.0.0.mysql.sql"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysqldb-root-password                                                 
      restartPolicy: Never
  backoffLimit: 1