apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: lakehouse
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lakehouse
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps" ]
  verbs: ["create", "get", "watch", "list", "post", "delete"  ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role-binding
  namespace: lakehouse
subjects:
- kind: ServiceAccount
  name: spark-sa
  namespace: lakehouse
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io