kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
  namespace: lakehouse
  labels:
    app: pg  
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
        app: spark
    spec:
      containers:
        - name: spark-worker
          image: spark-hadoop:3.2.0
          imagePullPolicy: IfNotPresent
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

